name: 'Protected Asset'
description: 'Unpack your protected .zip assets files using a password'
inputs:
  path:
    description: 'Path to folder with the zip files'
    required: true
    default: ''
  password:
    description: 'Password for the zip files'
    required: true
    default: ''
  output:
    description: 'Path to folder where to unpack the files (default: same folder as zip)'
    default: ''
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.path }}
    - ${{ inputs.password }}
    - ${{ inputs.output }}

branding:
  icon: 'archive'
  color: 'green'
