name: "Test Unpack and Pack"

on:
  push:
    branches:
      - master
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pack assets
        run: echo "super-secret-password-001" | ./pack.sh assets *.import

      - run: |
          if [ ! -f assets/sounds.7z ]; then
            echo "::error:: Sound archive missing"
            exit 1
          fi

          if [ ! -f assets/sprites.7z ]; then
            echo "::error:: Sprites archive missing"
            exit 1
          fi

      - name: Remove asset files
        run: rm -rf assets/sounds assets/sprites

      - name: Unpack assets
        uses: ./
        with:
          path: assets
          password: super-secret-password-001
      
      - run: |
          if [ ! -f assets/sounds/scream.mp3 ]; then
            echo "::error:: Sound file does not exist"
            exit 1
          fi

          if [ -f assets/sounds/scream.mp3.import ]; then
            echo "::error:: Sound import files should not exist"
            exit 1
          fi

          if [ ! -f assets/sprites/secret.png ]; then
            echo "::error:: Sprite file does not exist"
            exit 1
          fi

          if [ -f assets/sprites/secret.png.import ]; then
            echo "::error:: Sprite import files should not exist"
            exit 1
          fi
      