name: "Test Unpack and Pack"

on:
  push:
    branches:
      - master
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pack assets
        run: echo "super-secret-password-001" | ./pack.sh assets *.import

      - name: Verify assets packed
        uses: andstor/file-existence-action@v3
        with:
          files: "assets/sounds.7z, assets/sprites.7z"
          fail: true

      - name: Remove asset files
        run: rm -rf assets/sounds assets/sprites

      - name: Unpack assets
        uses: ./
        with:
          path: assets
          password: super-secret-password-001

      - name: Verify assets unpacked
        uses: andstor/file-existence-action@v3
        with:
          files: "assets/sounds/scream.mp3, assets/sprites/secret.png"
          fail: true
      
      - run: |
          if [ -f assets/sounds/scream.mp3.import ]; then
            exit 1
          fi

          if [ -f assets/sprites/secret.png.import ]; then
            exit 1
          fi
      